using Newtonsoft.Json;
using Phlank.ApiModeling.Extensions;
using System;
using System.Collections.Generic;
using System.Net;
using System.Text.Json.Serialization;

namespace Phlank.ApiModeling
{
    /// <summary>
    /// An error to be reflected by the API. This class follows the
    /// specification in
    /// <see href="https://www.rfc-editor.org/rfc/rfc7807.html">RFC7807</see>.
    /// </summary>
    public class ApiError
    {
        private HttpStatusCode _status;

        /// <summary>
        /// The HTTP status code generated by the origin server for this
        /// occurence of the problem.
        /// </summary>
        [System.Text.Json.Serialization.JsonIgnore]
        [Newtonsoft.Json.JsonIgnore]
        public HttpStatusCode Status
        {
            get => _status;
            init
            {
                if (!value.IsError())
                {
                    throw new ArgumentOutOfRangeException("Status must have a value greater than or equal to 400.");
                }
                else
                {
                    _status = value;
                }
            }
        }

        /// <summary>
        /// A URI reference that identifies the problem type. When this member
        /// is not present, its value is assumed to be "about:blank".
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        [JsonPropertyName("type")]
        public Uri Type { get; init; } = new Uri("about:blank");
        /// <summary>
        /// A short, human-readable summary of the problem type. It SHOULD NOT
        /// change from occurrence to occurrence of the problem, except for
        /// purposes of localization.
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        [JsonPropertyName("title")]
        public string Title { get; init; }
        /// <summary>
        /// A human-readable explanation specific to this occurrence of the
        /// problem.
        /// </summary>
        [JsonProperty(PropertyName = "detail")]
        [JsonPropertyName("detail")]
        public string Detail { get; init; }
        /// <summary>
        /// A URI reference that identifies the specific occurrence of the
        /// problem. It may or may not yield further information if
        /// dereferenced.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "instance")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("instance")]
        public Uri Instance { get; init; }
        /// <summary>
        /// Additional information to reflect back to the client. These items
        /// will be surfaced in the top level of the serialized response.
        /// </summary>
        [Newtonsoft.Json.JsonExtensionData]
        [System.Text.Json.Serialization.JsonExtensionData]
        public Dictionary<string, object> Extensions { get; init; } = new Dictionary<string, object>();
    }
}
