using Newtonsoft.Json;
using Phlank.Responder.Extensions;
using System;
using System.Collections.Generic;
using System.Net;
using System.Text.Json.Serialization;

namespace Phlank.Responder
{
    /// <summary>
    /// An error to be reflected by the API. This class follows the
    /// specification in
    /// <see href="https://www.rfc-editor.org/rfc/rfc7807.html">RFC7807</see>.
    /// At minimum, a user should provide values for Status, Title, and Details.
    /// </summary>
    public class ApiError
    {
        private static Dictionary<HttpStatusCode, Uri> Types = new Dictionary<HttpStatusCode, Uri>()
        {
            { HttpStatusCode.BadRequest, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.1") },
            { HttpStatusCode.PaymentRequired, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.2") },
            { HttpStatusCode.Forbidden, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.3") },
            { HttpStatusCode.NotFound, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.4") },
            { HttpStatusCode.MethodNotAllowed, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.5") },
            { HttpStatusCode.NotAcceptable, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.6") },
            { HttpStatusCode.RequestTimeout, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.7") },
            { HttpStatusCode.Conflict, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.8") },
            { HttpStatusCode.Gone, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.9") },
            { HttpStatusCode.LengthRequired, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.10") },
            { HttpStatusCode.RequestEntityTooLarge, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.11") },
            { HttpStatusCode.RequestUriTooLong, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.12") },
            { HttpStatusCode.UnsupportedMediaType, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.13") },
            { HttpStatusCode.ExpectationFailed, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.14") },
            { HttpStatusCode.UpgradeRequired, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.15") },
            { HttpStatusCode.InternalServerError, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.1") },
            { HttpStatusCode.NotImplemented, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.2") },
            { HttpStatusCode.BadGateway, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.3") },
            { HttpStatusCode.ServiceUnavailable, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.4") },
            { HttpStatusCode.GatewayTimeout, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.5") },
            { HttpStatusCode.HttpVersionNotSupported, new Uri("https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.6") }
        };

        private HttpStatusCode _status = HttpStatusCode.InternalServerError;
        private Uri _type;

        /// <summary>
        /// The HTTP status code generated by the origin server for this
        /// occurence of the problem.
        /// </summary>
        [System.Text.Json.Serialization.JsonIgnore]
        [Newtonsoft.Json.JsonIgnore]
        public HttpStatusCode Status
        {
            get => _status;
            set
            {
                if (!value.IsError())
                {
                    throw new ArgumentOutOfRangeException("Status must have a value greater than or equal to 400.");
                }
                else
                {
                    _status = value;
                }
            }
        }

        /// <summary>
        /// A URI reference that identifies the problem type. When this member
        /// is not specified, it will use a default <see cref="Uri"/> pointing
        /// to the RFC documentation of this error's Status.
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        [JsonPropertyName("type")]
        public Uri Type
        {
            get
            {
                if (_type != default)
                {
                    return _type;
                }
                else
                {
                    return Types.GetValueOrDefault(_status);
                }
            }
            set
            {
                _type = value;
            }
        }

        /// <summary>
        /// A short, human-readable summary of the problem type. It SHOULD NOT
        /// change from occurrence to occurrence of the problem, except for
        /// purposes of localization.
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the
        /// problem.
        /// </summary>
        [JsonProperty(PropertyName = "detail")]
        [JsonPropertyName("detail")]
        public string Detail { get; set; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the
        /// problem. It may or may not yield further information if
        /// dereferenced.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "instance")]
#if NET5_0_OR_GREATER
        [System.Text.Json.Serialization.JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
#endif
        [JsonPropertyName("instance")]
        public Uri Instance { get; set; }

        /// <summary>
        /// Additional information to reflect back to the client. These items
        /// will be surfaced in the top level of the serialized response.
        /// </summary>
        [Newtonsoft.Json.JsonExtensionData]
        [System.Text.Json.Serialization.JsonExtensionData]
        public Dictionary<string, object> Extensions { get; set; } = new Dictionary<string, object>();
    }
}
