using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net;
using System.Text.Json.Serialization;

namespace Phlank.Responder
{
    public class Response : ISuccessResponse, IProblemResponse
    {
        public bool IsSuccessful => Problem == null;

        public IDictionary<string, object> Extensions { get; set; }

        public Problem Problem { get; set; }
    }

    /// <summary>
    /// Content model for deserializing responses generated by the <see cref="IResponder"/>.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(ResponseNewtonsoftJsonConverter<>))]
    [System.Text.Json.Serialization.JsonConverter(typeof(ResponseSTJJsonConverter<>))]
    public class Response<T> : Response, ISuccessResponse<T> where T : class
    {
        public T Data { get; set; }
    }
}
