using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.Json;

namespace Phlank.Responder
{
    /// <summary>
    /// Model without data for deserializing responses generated by the <see cref="IResponder"/>.
    /// </summary>
    public class Response : ISuccessResponse, IProblemResponse
    {
        public bool IsSuccessful => Problem == null;

        public IDictionary<string, object> Extensions { get; set; } = new Dictionary<string, object>();

        public Problem Problem { get; set; }
    }

    /// <summary>
    /// Model with data for deserializing responses generated by the <see cref="IResponder"/>.
    /// </summary>
    public class Response<T> : Response, ISuccessResponse<T>
    {
        public T Data { get; set; }
    }
}
