using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net;
using System.Text.Json.Serialization;

namespace Phlank.Responder
{
    /// <summary>
    /// Content model for deserializing responses generated by the <see cref="IResponder"/>.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(ResponseNewtonsoftJsonConverter))]
    public class Response<T> : ISuccessResponse<T>, IProblemResponse where T : class
    {
        /// <summary>
        /// Additional, optional information that may be provided by the server regarding the operation.
        /// </summary>
        public IDictionary<string, object> Extensions { get; set; }

        /// <summary>
        /// The content to return back to the user as a result of the operation.
        /// </summary>
        public T Data { get; set; }

        public Problem Problem { get; set; }

        public bool IsSuccessful { get => Problem == null; }
    }
}
